import { NextResponse } from "next/server";

export const TEMPLATES = [
  {
    id: "t1",
    slug: "offer-letter-template",
    title: "Offer Letter Template",
    description: "A comprehensive, customizable US general offer letter template covering compensation, at-will employment, and benefits overview.",
    category: "Offer Letters",
    type: "Word (.docx)",
    downloads: 1450,
  },
  {
    id: "t2",
    slug: "employment-agreement-at-will",
    title: "Employment Agreement (At-Will, Full-Time)",
    description: "Standard employment contract outlining duties, compensation, non-solicitation, and at-will terms for full-time hires.",
    category: "Policies",
    type: "Word (.docx)",
    downloads: 890,
  },
  {
    id: "t3",
    slug: "employee-handbook-starter",
    title: "Employee Handbook Template",
    description: "A robust 75-page starter template covering workplace policies, code of conduct, PTO, benefits, and remote work guidelines.",
    category: "Policies",
    type: "Word (.docx)",
    downloads: 3200,
  },
  {
    id: "t4",
    slug: "i9-completion-checklist",
    title: "I-9 Completion Checklist",
    description: "Step-by-step checklist for HR managers and new hires to ensure I-9 compliance and proper documentation handling.",
    category: "Compliance",
    type: "PDF",
    downloads: 2100,
  },
  {
    id: "t5",
    slug: "payroll-calendar-2025-2026",
    title: "Payroll Calendar 2025/2026",
    description: "An interactive Excel calendar with federal bank holidays, semi-monthly/bi-weekly pay dates, and processing deadlines.",
    category: "Payroll",
    type: "Excel (.xlsx)",
    downloads: 5400,
  },
  {
    id: "t6",
    slug: "new-hire-onboarding-checklist",
    title: "New Hire Onboarding Checklist",
    description: "Ensure a smooth Day 1. Covers IT setup, paperwork, 30/60/90-day check-ins, and team integrations.",
    category: "Onboarding",
    type: "PDF",
    downloads: 4100,
  },
  {
    id: "t7",
    slug: "annual-performance-review",
    title: "Performance Review Template",
    description: "Annual and quarterly review template for managers to assess KPIs, core values alignment, and career growth.",
    category: "Policies",
    type: "Word (.docx)",
    downloads: 1800,
  },
  {
    id: "t8",
    slug: "pto-request-form",
    title: "PTO Request Form",
    description: "Standardized request form for paid time off, sick leave, and unpaid leave tracking.",
    category: "Policies",
    type: "PDF",
    downloads: 950,
  },
  {
    id: "t9",
    slug: "expense-report-template",
    title: "Expense Report Template",
    description: "Easily track employee reimbursements, travel expenses, and stipends with auto-calculating Excel formulas.",
    category: "Payroll",
    type: "Excel (.xlsx)",
    downloads: 1200,
  },
  {
    id: "t10",
    slug: "remote-work-policy",
    title: "Remote Work Policy Template",
    description: "Clear guidelines on remote equipment stipends, working hours, communication expectations, and security protocols.",
    category: "Policies",
    type: "Word (.docx)",
    downloads: 2900,
  },
  {
    id: "t11",
    slug: "non-disclosure-agreement-nda",
    title: "Non-Disclosure Agreement (NDA)",
    description: "Standard one-way and mutual NDA template to protect your company's intellectual property and trade secrets.",
    category: "Compliance",
    type: "Word (.docx)",
    downloads: 3600,
  },
  {
    id: "t12",
    slug: "independent-contractor-agreement",
    title: "Independent Contractor Agreement",
    description: "Contract template for freelancers and 1099 workers detailing scope of work, payment terms, and intellectual property assignment.",
    category: "Compliance",
    type: "Word (.docx)",
    downloads: 2750,
  }
];

export async function GET() {
  return NextResponse.json({ templates: TEMPLATES });
}
