export type EmailCategory =
  | "Payroll"
  | "Auth"
  | "HR"
  | "Benefits"
  | "Hiring"
  | "Compliance & Billing";

export type EmailTone = "default" | "danger" | "success";

export type EmailBlock =
  | { type: "text"; value: string }
  | { type: "alert"; value: string }
  | { type: "list"; title?: string; items: string[] }
  | { type: "table"; rows: Array<{ label: string; value: string }> }
  | { type: "legal"; value: string };

export type EmailCta = {
  label: string;
  href: string;
  tone?: "primary" | "danger" | "secondary";
};

export type BaseEmailProps = {
  companyName?: string;
};

export type EmailTemplateDefinition = {
  slug: EmailTemplateSlug;
  componentName: string;
  category: EmailCategory;
  subject: string;
  preheader: string;
  title: string;
  eyebrow?: string;
  tone?: EmailTone;
  requiredProps: readonly string[];
  blocks: readonly EmailBlock[];
  ctas?: readonly EmailCta[];
};

export const emailTemplateSampleProps = {
  pay_stub_ready: {
    companyName: "Acme Robotics",
    employeeName: "Maya Patel",
    periodStart: "May 11, 2026",
    periodEnd: "May 24, 2026",
    grossPay: "$4,850.00",
    deductions: "$1,124.35",
    netPay: "$3,725.65",
    payStubUrl: "https://app.circleworks.com/me/paystubs/2026-05-24",
    hrEmail: "hr@acmerobotics.com",
  },
  payroll_run_submitted: {
    companyName: "Acme Robotics",
    payrollAdminName: "Noah Kim",
    payPeriod: "May 11 - May 24, 2026",
    checkDate: "May 29, 2026",
    employeeCount: "148",
    totalGross: "$412,880.00",
    approverName: "Avery Johnson",
    approveUrl: "https://app.circleworks.com/payroll/approve/magic-approve",
    rejectUrl: "https://app.circleworks.com/payroll/approve/magic-reject",
  },
  payroll_run_approved: {
    companyName: "Acme Robotics",
    approverName: "Avery Johnson",
    payPeriod: "May 11 - May 24, 2026",
    checkDate: "May 29, 2026",
    employeeCount: "148",
    totalGross: "$412,880.00",
    viewRunUrl: "https://app.circleworks.com/payroll/runs/pr-2026-05-29",
  },
  payroll_run_failed: {
    companyName: "Acme Robotics",
    payPeriod: "May 11 - May 24, 2026",
    failureReason: "ACH funding account was declined by the bank.",
    failedAt: "May 29, 2026 at 9:14 AM PT",
    resolveUrl: "https://app.circleworks.com/payroll/runs/pr-2026-05-29/issues",
  },
  tax_filing_confirmation: {
    companyName: "Acme Robotics",
    formType: "Form 941",
    filingPeriod: "Q2 2026",
    amountPaid: "$18,240.18",
    confirmationNumber: "IRS-941-2026-Q2-88421",
    jurisdiction: "Federal",
  },
  w2_available: {
    companyName: "Acme Robotics",
    employeeName: "Maya Patel",
    taxYear: "2026",
    downloadUrl: "https://app.circleworks.com/me/w2/2026",
    filingDeadline: "April 15, 2027",
  },
  direct_deposit_failed: {
    companyName: "Acme Robotics",
    employeeName: "Chris Wong",
    failedAmount: "$3,725.65",
    bankLast4: "8831",
    fixBankUrl: "https://app.circleworks.com/me/profile/bank",
    supportEmail: "payroll@acmerobotics.com",
  },
  garnishment_added: {
    companyName: "Acme Robotics",
    employeeName: "Noah Kim",
    garnishmentType: "Child support",
    amount: "$350.00 per pay period",
    startDate: "June 12, 2026",
    orderId: "CA-CS-44921",
    viewGarnishmentUrl: "https://app.circleworks.com/payroll/garnishments/CA-CS-44921",
  },
  off_cycle_processed: {
    companyName: "Acme Robotics",
    amount: "$18,450.00",
    employeeCount: "5",
    checkDate: "May 31, 2026",
    runId: "OC-2026-0531",
    viewRunUrl: "https://app.circleworks.com/payroll/runs/OC-2026-0531",
  },
  payroll_reminder: {
    companyName: "Acme Robotics",
    daysUntilDue: "2",
    payPeriod: "May 25 - June 7, 2026",
    checkDate: "June 12, 2026",
    startRunUrl: "https://app.circleworks.com/payroll/run",
  },
  welcome_new_user: {
    companyName: "Acme Robotics",
    name: "Maya",
    setupUrl: "https://app.circleworks.com/welcome/setup",
  },
  email_verification: {
    companyName: "Acme Robotics",
    name: "Maya",
    verifyUrl: "https://app.circleworks.com/auth/verify-email/token",
    expiresAt: "24 hours",
  },
  password_reset: {
    companyName: "Acme Robotics",
    name: "Maya",
    resetUrl: "https://app.circleworks.com/reset-password/token",
    expiresInMinutes: "15",
  },
  invitation_to_company: {
    companyName: "Acme Robotics",
    inviterName: "Avery Johnson",
    role: "Payroll Manager",
    acceptUrl: "https://app.circleworks.com/invitations/accept/token",
  },
  mfa_setup_reminder: {
    companyName: "Acme Robotics",
    name: "Maya",
    enableMfaUrl: "https://app.circleworks.com/settings/security",
  },
  employee_onboarding_welcome: {
    companyName: "Acme Robotics",
    employeeName: "Jordan Lee",
    firstDay: "June 10, 2026",
    managerName: "Maya Patel",
    managerEmail: "maya@acmerobotics.com",
    officeAddress: "548 Market St, San Francisco, CA 94104",
    onboardingUrl: "https://app.circleworks.com/onboarding/jordan",
    checklistItems: "Complete profile; Upload I-9 documents; Add direct deposit; Review handbook",
  },
  onboarding_task_assigned: {
    companyName: "Acme Robotics",
    employeeName: "Jordan Lee",
    taskName: "Upload I-9 identity documents",
    dueDate: "June 7, 2026",
    taskUrl: "https://app.circleworks.com/onboarding/tasks/i9",
  },
  document_expiry_warning: {
    companyName: "Acme Robotics",
    employeeName: "Jordan Lee",
    documentName: "I-9 work authorization",
    expiryDate: "June 30, 2026",
    updateDocumentUrl: "https://app.circleworks.com/me/documents/i9",
  },
  pto_request_submitted: {
    companyName: "Acme Robotics",
    managerName: "Avery Johnson",
    employeeName: "Maya Patel",
    dates: "July 8 - July 12, 2026",
    days: "5",
    reason: "Family vacation",
    approveUrl: "https://app.circleworks.com/time/pto/approve/magic",
    denyUrl: "https://app.circleworks.com/time/pto/deny/magic",
  },
  pto_approved: {
    companyName: "Acme Robotics",
    employeeName: "Maya Patel",
    dates: "July 8 - July 12, 2026",
    days: "5",
    approverName: "Avery Johnson",
  },
  pto_denied: {
    companyName: "Acme Robotics",
    employeeName: "Maya Patel",
    dates: "July 8 - July 12, 2026",
    managerReason: "Coverage is too thin during the launch week.",
    remainingBalance: "64 hours",
  },
  employee_anniversary: {
    companyName: "Acme Robotics",
    employeeName: "Maya Patel",
    years: "3",
    customNote: "Thank you for building calm, reliable payroll operations for every team.",
  },
  termination_confirmation: {
    companyName: "Acme Robotics",
    employeeName: "Sam Rivera",
    lastDay: "June 14, 2026",
    finalPayDate: "June 21, 2026",
    cobraNoticeUrl: "https://app.circleworks.com/me/cobra/notice",
    equipmentChecklist: "Laptop; Badge; Security key; Parking pass",
  },
  open_enrollment_started: {
    companyName: "Acme Robotics",
    employeeName: "Maya Patel",
    enrollmentDeadline: "November 18, 2026",
    enrollUrl: "https://app.circleworks.com/benefits/enrollment",
    changesThisYear: "New PPO option, higher HSA employer match, and expanded mental health coverage",
  },
  enrollment_closing_soon: {
    companyName: "Acme Robotics",
    employeeName: "Maya Patel",
    enrollmentDeadline: "November 18, 2026",
    completeEnrollmentUrl: "https://app.circleworks.com/benefits/enrollment",
  },
  enrollment_confirmation: {
    companyName: "Acme Robotics",
    employeeName: "Maya Patel",
    selectedPlans: "Medical PPO; Dental Premium; Vision; HSA",
    deductionsPerPaycheck: "$184.20",
    benefitsUrl: "https://app.circleworks.com/me/benefits",
  },
  qle_approved: {
    companyName: "Acme Robotics",
    employeeName: "Maya Patel",
    eventType: "Marriage",
    windowStart: "May 30, 2026",
    windowEnd: "June 29, 2026",
    enrollUrl: "https://app.circleworks.com/benefits/qle/enroll",
  },
  cobra_notice: {
    companyName: "Acme Robotics",
    employeeName: "Sam Rivera",
    planCosts: "Medical PPO: $642.18/mo; Dental: $44.10/mo; Vision: $12.25/mo",
    electionDeadline: "August 13, 2026",
    qualifyingEventDate: "June 14, 2026",
    cobraUrl: "https://app.circleworks.com/me/cobra/notice",
  },
  candidate_application_received: {
    companyName: "Acme Robotics",
    candidateName: "Nia Rivera",
    role: "Senior Backend Engineer",
    careersUrl: "https://acmerobotics.com/careers",
  },
  interview_scheduled: {
    companyName: "Acme Robotics",
    candidateName: "Nia Rivera",
    role: "Senior Backend Engineer",
    interviewDate: "June 4, 2026",
    interviewTime: "10:30 AM PT",
    locationOrVideoLink: "https://meet.example.com/acme-engineering",
    interviewers: "Maya Patel, Chris Wong",
    calendarUrl: "https://app.circleworks.com/hiring/interviews/ics/abc123",
  },
  offer_letter_sent: {
    companyName: "Acme Robotics",
    candidateName: "Nia Rivera",
    role: "Senior Backend Engineer",
    reviewOfferUrl: "https://docusign.example.com/offer/abc123",
  },
  offer_accepted_hr_notify: {
    companyName: "Acme Robotics",
    candidateName: "Nia Rivera",
    role: "Senior Backend Engineer",
    startDate: "July 8, 2026",
    startOnboardingUrl: "https://app.circleworks.com/onboarding/start/nia",
  },
  offer_declined_hr_notify: {
    companyName: "Acme Robotics",
    candidateName: "Nia Rivera",
    role: "Senior Backend Engineer",
    declineReason: "Accepted another offer closer to home.",
    candidateProfileUrl: "https://app.circleworks.com/hiring/candidates/nia",
  },
  candidate_rejected: {
    companyName: "Acme Robotics",
    candidateName: "Nia Rivera",
    role: "Senior Backend Engineer",
    careersUrl: "https://acmerobotics.com/careers",
  },
  background_check_initiated: {
    companyName: "Acme Robotics",
    candidateName: "Nia Rivera",
    provider: "Checkr",
    estimatedTimeline: "2-3 business days",
    statusUrl: "https://app.circleworks.com/hiring/background-checks/nia",
  },
  compliance_alert_critical: {
    companyName: "Acme Robotics",
    issueDescription: "California new hire report is overdue for two employees.",
    severity: "Critical",
    dueDate: "Today",
    resolveUrl: "https://app.circleworks.com/compliance/dashboard/issues/critical",
  },
  i9_expiring_warning: {
    companyName: "Acme Robotics",
    employeeName: "Jordan Lee",
    documentName: "I-9 work authorization",
    expiryDate: "June 30, 2026",
    reverifyUrl: "https://app.circleworks.com/compliance/i9/jordan",
  },
  filing_deadline_reminder: {
    companyName: "Acme Robotics",
    daysUntilDue: "5",
    formType: "Form 941",
    dueDate: "July 31, 2026",
    jurisdiction: "Federal",
    filingUrl: "https://app.circleworks.com/compliance/federal-filings/941",
  },
  invoice_created: {
    companyName: "Acme Robotics",
    amount: "$1,240.00",
    billingPeriod: "May 2026",
    dueDate: "June 15, 2026",
    invoiceUrl: "https://app.circleworks.com/settings/billing/invoices/inv-2026-05",
  },
  payment_failed: {
    companyName: "Acme Robotics",
    amount: "$1,240.00",
    failureReason: "Card ending 4242 was declined.",
    updatePaymentUrl: "https://app.circleworks.com/settings/billing/payment-method",
  },
  trial_expiring: {
    companyName: "Acme Robotics",
    trialEndDate: "June 2, 2026",
    featuresSummary: "Payroll automation, onboarding workflows, compliance alerts, and analytics",
    upgradeUrl: "https://app.circleworks.com/settings/billing/upgrade",
  },
  subscription_upgraded: {
    companyName: "Acme Robotics",
    planName: "CircleWorks Pro",
    featuresUnlocked: "Automation builder; Advanced reports; Multi-state compliance; Priority support",
    exploreUrl: "https://app.circleworks.com/product/pro",
  },
  subscription_cancelled: {
    companyName: "Acme Robotics",
    effectiveDate: "June 30, 2026",
    dataExportUrl: "https://app.circleworks.com/settings/export",
    winBackOffer: "Come back within 30 days and keep your current implementation credits.",
  },
  data_export_ready: {
    companyName: "Acme Robotics",
    downloadUrl: "https://app.circleworks.com/settings/export/download/abc123",
    expiresAt: "72 hours",
  },
  security_alert: {
    companyName: "Acme Robotics",
    location: "Austin, TX",
    device: "Chrome on macOS",
    timestamp: "May 30, 2026 at 11:42 AM PT",
    wasThisYouUrl: "https://app.circleworks.com/settings/security/activity/confirm",
    secureAccountUrl: "https://app.circleworks.com/settings/security",
  },
} as const;

type SamplePropsBySlug = typeof emailTemplateSampleProps;
export type EmailTemplateSlug = keyof SamplePropsBySlug;

type WidenStringProps<T> = {
  [K in keyof T]: T[K] extends string ? string : T[K];
};

export type TemplateProps<TSlug extends EmailTemplateSlug> = BaseEmailProps &
  WidenStringProps<SamplePropsBySlug[TSlug]>;

export const emailTemplateDefinitions: readonly EmailTemplateDefinition[] = [
  {
    slug: "pay_stub_ready",
    componentName: "PayStubReadyEmail",
    category: "Payroll",
    subject: "Your pay stub is ready",
    preheader: "Your pay stub for {{periodStart}} - {{periodEnd}} is ready.",
    title: "Your pay stub is ready",
    requiredProps: ["employeeName", "periodStart", "periodEnd", "grossPay", "deductions", "netPay", "payStubUrl", "hrEmail"],
    blocks: [
      { type: "text", value: "Hi {{employeeName}}, your pay stub for {{periodStart}} through {{periodEnd}} is available in CircleWorks." },
      { type: "table", rows: [{ label: "Gross pay", value: "{{grossPay}}" }, { label: "Deductions", value: "{{deductions}}" }, { label: "Net pay", value: "{{netPay}}" }] },
      { type: "text", value: "Questions? Contact HR at {{hrEmail}}." },
    ],
    ctas: [{ label: "View Pay Stub", href: "{{payStubUrl}}" }],
  },
  {
    slug: "payroll_run_submitted",
    componentName: "PayrollRunSubmittedEmail",
    category: "Payroll",
    subject: "Payroll submitted for approval",
    preheader: "{{payrollAdminName}} submitted payroll for {{payPeriod}}.",
    title: "Payroll submitted for approval",
    requiredProps: ["payrollAdminName", "payPeriod", "checkDate", "employeeCount", "totalGross", "approverName", "approveUrl", "rejectUrl"],
    blocks: [
      { type: "text", value: "{{payrollAdminName}} submitted payroll for {{approverName}} to review." },
      { type: "table", rows: [{ label: "Pay period", value: "{{payPeriod}}" }, { label: "Check date", value: "{{checkDate}}" }, { label: "Employees", value: "{{employeeCount}}" }, { label: "Total gross", value: "{{totalGross}}" }] },
    ],
    ctas: [{ label: "Approve Payroll", href: "{{approveUrl}}" }, { label: "Reject", href: "{{rejectUrl}}", tone: "secondary" }],
  },
  {
    slug: "payroll_run_approved",
    componentName: "PayrollRunApprovedEmail",
    category: "Payroll",
    subject: "Payroll run approved",
    preheader: "{{approverName}} approved payroll for {{payPeriod}}.",
    title: "Payroll run approved",
    tone: "success",
    requiredProps: ["approverName", "payPeriod", "checkDate", "employeeCount", "totalGross", "viewRunUrl"],
    blocks: [
      { type: "text", value: "{{approverName}} approved this payroll run." },
      { type: "table", rows: [{ label: "Pay period", value: "{{payPeriod}}" }, { label: "Check date", value: "{{checkDate}}" }, { label: "Employees", value: "{{employeeCount}}" }, { label: "Total gross", value: "{{totalGross}}" }] },
    ],
    ctas: [{ label: "View Run", href: "{{viewRunUrl}}" }],
  },
  {
    slug: "payroll_run_failed",
    componentName: "PayrollRunFailedEmail",
    category: "Payroll",
    subject: "Payroll run failed - action required",
    preheader: "Payroll for {{payPeriod}} failed and needs attention.",
    title: "Payroll run failed - action required",
    tone: "danger",
    requiredProps: ["payPeriod", "failureReason", "failedAt", "resolveUrl"],
    blocks: [
      { type: "alert", value: "High priority: payroll did not process successfully." },
      { type: "table", rows: [{ label: "Pay period", value: "{{payPeriod}}" }, { label: "Failed at", value: "{{failedAt}}" }, { label: "Reason", value: "{{failureReason}}" }] },
    ],
    ctas: [{ label: "Resolve Issue", href: "{{resolveUrl}}", tone: "danger" }],
  },
  {
    slug: "tax_filing_confirmation",
    componentName: "TaxFilingConfirmationEmail",
    category: "Payroll",
    subject: "Tax filing confirmed",
    preheader: "{{formType}} for {{filingPeriod}} was filed.",
    title: "Tax filing confirmed",
    tone: "success",
    requiredProps: ["formType", "filingPeriod", "amountPaid", "confirmationNumber", "jurisdiction"],
    blocks: [{ type: "table", rows: [{ label: "Form", value: "{{formType}}" }, { label: "Period", value: "{{filingPeriod}}" }, { label: "Jurisdiction", value: "{{jurisdiction}}" }, { label: "Amount paid", value: "{{amountPaid}}" }, { label: "Confirmation", value: "{{confirmationNumber}}" }] }],
  },
  {
    slug: "w2_available",
    componentName: "W2AvailableEmail",
    category: "Payroll",
    subject: "Your W-2 is ready for {{taxYear}}",
    preheader: "Download your {{taxYear}} W-2 before the filing deadline.",
    title: "Your W-2 is ready for {{taxYear}}",
    requiredProps: ["employeeName", "taxYear", "downloadUrl", "filingDeadline"],
    blocks: [
      { type: "text", value: "Hi {{employeeName}}, your W-2 for {{taxYear}} is ready in CircleWorks." },
      { type: "alert", value: "Reminder: individual tax filing deadline is {{filingDeadline}}." },
    ],
    ctas: [{ label: "Download W-2", href: "{{downloadUrl}}" }],
  },
  {
    slug: "direct_deposit_failed",
    componentName: "DirectDepositFailedEmail",
    category: "Payroll",
    subject: "Direct deposit failed - action required",
    preheader: "Direct deposit for {{employeeName}} could not be completed.",
    title: "Direct deposit failed - action required",
    tone: "danger",
    requiredProps: ["employeeName", "failedAmount", "bankLast4", "fixBankUrl", "supportEmail"],
    blocks: [
      { type: "text", value: "The direct deposit for {{employeeName}} failed for bank account ending {{bankLast4}}." },
      { type: "table", rows: [{ label: "Failed amount", value: "{{failedAmount}}" }, { label: "Next step", value: "Update bank details or contact {{supportEmail}}" }] },
    ],
    ctas: [{ label: "Fix Direct Deposit", href: "{{fixBankUrl}}", tone: "danger" }],
  },
  {
    slug: "garnishment_added",
    componentName: "GarnishmentAddedEmail",
    category: "Payroll",
    subject: "New garnishment order added",
    preheader: "{{garnishmentType}} garnishment added for {{employeeName}}.",
    title: "New garnishment order added",
    requiredProps: ["employeeName", "garnishmentType", "amount", "startDate", "orderId", "viewGarnishmentUrl"],
    blocks: [{ type: "table", rows: [{ label: "Employee", value: "{{employeeName}}" }, { label: "Type", value: "{{garnishmentType}}" }, { label: "Amount", value: "{{amount}}" }, { label: "Start date", value: "{{startDate}}" }, { label: "Order ID", value: "{{orderId}}" }] }],
    ctas: [{ label: "View Garnishment", href: "{{viewGarnishmentUrl}}" }],
  },
  {
    slug: "off_cycle_processed",
    componentName: "OffCycleProcessedEmail",
    category: "Payroll",
    subject: "Off-cycle payroll processed",
    preheader: "Off-cycle payroll {{runId}} was processed for {{employeeCount}} employees.",
    title: "Off-cycle payroll processed",
    tone: "success",
    requiredProps: ["amount", "employeeCount", "checkDate", "runId", "viewRunUrl"],
    blocks: [{ type: "table", rows: [{ label: "Run ID", value: "{{runId}}" }, { label: "Amount", value: "{{amount}}" }, { label: "Employees", value: "{{employeeCount}}" }, { label: "Check date", value: "{{checkDate}}" }] }],
    ctas: [{ label: "View Run", href: "{{viewRunUrl}}" }],
  },
  {
    slug: "payroll_reminder",
    componentName: "PayrollReminderEmail",
    category: "Payroll",
    subject: "Payroll due in {{daysUntilDue}} days",
    preheader: "Start payroll for {{payPeriod}} before the cutoff.",
    title: "Payroll due in {{daysUntilDue}} days",
    requiredProps: ["daysUntilDue", "payPeriod", "checkDate", "startRunUrl"],
    blocks: [{ type: "table", rows: [{ label: "Pay period", value: "{{payPeriod}}" }, { label: "Check date", value: "{{checkDate}}" }, { label: "Due in", value: "{{daysUntilDue}} days" }] }],
    ctas: [{ label: "Start Run", href: "{{startRunUrl}}" }],
  },
  {
    slug: "welcome_new_user",
    componentName: "WelcomeNewUserEmail",
    category: "Auth",
    subject: "Welcome to CircleWorks",
    preheader: "Set up your account for {{companyName}}.",
    title: "Welcome to CircleWorks",
    requiredProps: ["name", "companyName", "setupUrl"],
    blocks: [
      { type: "text", value: "Hi {{name}}, your CircleWorks account for {{companyName}} is ready." },
      { type: "list", title: "Quick start checklist", items: ["Confirm your profile", "Invite your team", "Review payroll and HR settings"] },
    ],
    ctas: [{ label: "Set up your account", href: "{{setupUrl}}" }],
  },
  {
    slug: "email_verification",
    componentName: "EmailVerificationEmail",
    category: "Auth",
    subject: "Verify your email address",
    preheader: "Your email verification link expires in {{expiresAt}}.",
    title: "Verify your email address",
    requiredProps: ["name", "verifyUrl", "expiresAt"],
    blocks: [
      { type: "text", value: "Hi {{name}}, verify your email address to finish setting up CircleWorks." },
      { type: "alert", value: "This magic link expires in {{expiresAt}}." },
    ],
    ctas: [{ label: "Verify Email", href: "{{verifyUrl}}" }],
  },
  {
    slug: "password_reset",
    componentName: "PasswordResetEmail",
    category: "Auth",
    subject: "Reset your password",
    preheader: "Your password reset link expires in {{expiresInMinutes}} minutes.",
    title: "Reset your password",
    requiredProps: ["name", "resetUrl", "expiresInMinutes"],
    blocks: [
      { type: "text", value: "Hi {{name}}, use the secure link below to reset your password." },
      { type: "alert", value: "This link expires in {{expiresInMinutes}} minutes. If you did not request this, you can ignore this email or secure your account." },
    ],
    ctas: [{ label: "Reset Password", href: "{{resetUrl}}" }],
  },
  {
    slug: "invitation_to_company",
    componentName: "InvitationToCompanyEmail",
    category: "Auth",
    subject: "You've been invited to {{companyName}} on CircleWorks",
    preheader: "{{inviterName}} invited you as {{role}}.",
    title: "You've been invited to {{companyName}}",
    requiredProps: ["inviterName", "companyName", "role", "acceptUrl"],
    blocks: [{ type: "table", rows: [{ label: "Inviter", value: "{{inviterName}}" }, { label: "Company", value: "{{companyName}}" }, { label: "Role", value: "{{role}}" }] }],
    ctas: [{ label: "Accept Invitation", href: "{{acceptUrl}}" }],
  },
  {
    slug: "mfa_setup_reminder",
    componentName: "MfaSetupReminderEmail",
    category: "Auth",
    subject: "Enable two-factor authentication",
    preheader: "Add an extra security layer to your CircleWorks account.",
    title: "Enable two-factor authentication",
    requiredProps: ["name", "enableMfaUrl"],
    blocks: [
      { type: "text", value: "Hi {{name}}, two-factor authentication helps protect payroll, HR, and employee data even if a password is exposed." },
      { type: "list", title: "Security benefits", items: ["Blocks most stolen-password attacks", "Protects payroll approvals", "Meets stronger internal access controls"] },
    ],
    ctas: [{ label: "Enable MFA", href: "{{enableMfaUrl}}" }],
  },
  {
    slug: "employee_onboarding_welcome",
    componentName: "EmployeeOnboardingWelcomeEmail",
    category: "HR",
    subject: "Welcome to {{companyName}}! Your first day is {{firstDay}}",
    preheader: "Your onboarding checklist and manager contact are ready.",
    title: "Welcome to {{companyName}}!",
    requiredProps: ["employeeName", "companyName", "firstDay", "managerName", "managerEmail", "officeAddress", "onboardingUrl", "checklistItems"],
    blocks: [
      { type: "text", value: "Hi {{employeeName}}, we are excited for your first day on {{firstDay}}." },
      { type: "table", rows: [{ label: "Manager", value: "{{managerName}} ({{managerEmail}})" }, { label: "Office", value: "{{officeAddress}}" }] },
      { type: "list", title: "Onboarding checklist", items: ["{{checklistItems}}"] },
    ],
    ctas: [{ label: "Start Onboarding", href: "{{onboardingUrl}}" }],
  },
  {
    slug: "onboarding_task_assigned",
    componentName: "OnboardingTaskAssignedEmail",
    category: "HR",
    subject: "You have a new onboarding task",
    preheader: "{{taskName}} is due {{dueDate}}.",
    title: "You have a new onboarding task",
    requiredProps: ["employeeName", "taskName", "dueDate", "taskUrl"],
    blocks: [{ type: "table", rows: [{ label: "Employee", value: "{{employeeName}}" }, { label: "Task", value: "{{taskName}}" }, { label: "Due date", value: "{{dueDate}}" }] }],
    ctas: [{ label: "Complete Task", href: "{{taskUrl}}" }],
  },
  {
    slug: "document_expiry_warning",
    componentName: "DocumentExpiryWarningEmail",
    category: "HR",
    subject: "Your {{documentName}} expires in 30 days",
    preheader: "Update {{documentName}} before {{expiryDate}}.",
    title: "Your {{documentName}} expires in 30 days",
    tone: "danger",
    requiredProps: ["employeeName", "documentName", "expiryDate", "updateDocumentUrl"],
    blocks: [{ type: "text", value: "Hi {{employeeName}}, your {{documentName}} expires on {{expiryDate}}. Please update it before the expiration date." }],
    ctas: [{ label: "Update Document", href: "{{updateDocumentUrl}}" }],
  },
  {
    slug: "pto_request_submitted",
    componentName: "PtoRequestSubmittedEmail",
    category: "HR",
    subject: "{{employeeName}} requested PTO",
    preheader: "{{employeeName}} requested {{days}} days off.",
    title: "{{employeeName}} requested PTO",
    requiredProps: ["managerName", "employeeName", "dates", "days", "reason", "approveUrl", "denyUrl"],
    blocks: [
      { type: "text", value: "Hi {{managerName}}, review the PTO request below." },
      { type: "table", rows: [{ label: "Employee", value: "{{employeeName}}" }, { label: "Dates", value: "{{dates}}" }, { label: "Days", value: "{{days}}" }, { label: "Reason", value: "{{reason}}" }] },
    ],
    ctas: [{ label: "Approve", href: "{{approveUrl}}" }, { label: "Deny", href: "{{denyUrl}}", tone: "secondary" }],
  },
  {
    slug: "pto_approved",
    componentName: "PtoApprovedEmail",
    category: "HR",
    subject: "Your PTO has been approved",
    preheader: "{{approverName}} approved {{days}} days off.",
    title: "Your PTO has been approved",
    tone: "success",
    requiredProps: ["employeeName", "dates", "days", "approverName"],
    blocks: [{ type: "table", rows: [{ label: "Employee", value: "{{employeeName}}" }, { label: "Dates", value: "{{dates}}" }, { label: "Days", value: "{{days}}" }, { label: "Approver", value: "{{approverName}}" }] }],
  },
  {
    slug: "pto_denied",
    componentName: "PtoDeniedEmail",
    category: "HR",
    subject: "Your PTO request was not approved",
    preheader: "Review the manager note and your remaining balance.",
    title: "Your PTO request was not approved",
    requiredProps: ["employeeName", "dates", "managerReason", "remainingBalance"],
    blocks: [{ type: "table", rows: [{ label: "Employee", value: "{{employeeName}}" }, { label: "Dates", value: "{{dates}}" }, { label: "Manager note", value: "{{managerReason}}" }, { label: "Remaining balance", value: "{{remainingBalance}}" }] }],
  },
  {
    slug: "employee_anniversary",
    componentName: "EmployeeAnniversaryEmail",
    category: "HR",
    subject: "Happy work anniversary!",
    preheader: "Celebrating {{years}} years at {{companyName}}.",
    title: "Happy work anniversary!",
    requiredProps: ["employeeName", "years", "customNote", "companyName"],
    blocks: [
      { type: "text", value: "Hi {{employeeName}}, happy {{years}} year work anniversary at {{companyName}}." },
      { type: "text", value: "{{customNote}}" },
    ],
  },
  {
    slug: "termination_confirmation",
    componentName: "TerminationConfirmationEmail",
    category: "HR",
    subject: "Employment separation confirmed",
    preheader: "Review final pay, COBRA, and equipment return details.",
    title: "Employment separation confirmed",
    requiredProps: ["employeeName", "lastDay", "finalPayDate", "cobraNoticeUrl", "equipmentChecklist"],
    blocks: [
      { type: "table", rows: [{ label: "Employee", value: "{{employeeName}}" }, { label: "Last day", value: "{{lastDay}}" }, { label: "Final pay date", value: "{{finalPayDate}}" }] },
      { type: "list", title: "Return equipment checklist", items: ["{{equipmentChecklist}}"] },
    ],
    ctas: [{ label: "View COBRA Notice", href: "{{cobraNoticeUrl}}" }],
  },
  {
    slug: "open_enrollment_started",
    componentName: "OpenEnrollmentStartedEmail",
    category: "Benefits",
    subject: "Open enrollment is now open - enroll by {{enrollmentDeadline}}",
    preheader: "Benefits enrollment is open for {{companyName}}.",
    title: "Open enrollment is now open",
    requiredProps: ["employeeName", "enrollmentDeadline", "enrollUrl", "changesThisYear"],
    blocks: [
      { type: "text", value: "Hi {{employeeName}}, open enrollment is live. Enroll by {{enrollmentDeadline}}." },
      { type: "alert", value: "What's changed this year: {{changesThisYear}}" },
    ],
    ctas: [{ label: "Enroll Now", href: "{{enrollUrl}}" }],
  },
  {
    slug: "enrollment_closing_soon",
    componentName: "EnrollmentClosingSoonEmail",
    category: "Benefits",
    subject: "2 days left to enroll in benefits",
    preheader: "Complete enrollment by {{enrollmentDeadline}}.",
    title: "2 days left to enroll in benefits",
    tone: "danger",
    requiredProps: ["employeeName", "enrollmentDeadline", "completeEnrollmentUrl"],
    blocks: [{ type: "text", value: "Hi {{employeeName}}, benefits enrollment closes on {{enrollmentDeadline}}. Complete your elections now to avoid missing coverage." }],
    ctas: [{ label: "Complete Enrollment", href: "{{completeEnrollmentUrl}}", tone: "danger" }],
  },
  {
    slug: "enrollment_confirmation",
    componentName: "EnrollmentConfirmationEmail",
    category: "Benefits",
    subject: "Benefits enrollment confirmed",
    preheader: "Your selected plans and deductions are confirmed.",
    title: "Benefits enrollment confirmed",
    tone: "success",
    requiredProps: ["employeeName", "selectedPlans", "deductionsPerPaycheck", "benefitsUrl"],
    blocks: [{ type: "table", rows: [{ label: "Employee", value: "{{employeeName}}" }, { label: "Selected plans", value: "{{selectedPlans}}" }, { label: "Deductions per paycheck", value: "{{deductionsPerPaycheck}}" }] }],
    ctas: [{ label: "View Benefits", href: "{{benefitsUrl}}" }],
  },
  {
    slug: "qle_approved",
    componentName: "QleApprovedEmail",
    category: "Benefits",
    subject: "Life event enrollment window open",
    preheader: "{{eventType}} enrollment window runs {{windowStart}} - {{windowEnd}}.",
    title: "Life event enrollment window open",
    requiredProps: ["employeeName", "eventType", "windowStart", "windowEnd", "enrollUrl"],
    blocks: [{ type: "table", rows: [{ label: "Employee", value: "{{employeeName}}" }, { label: "Event type", value: "{{eventType}}" }, { label: "Window", value: "{{windowStart}} - {{windowEnd}}" }] }],
    ctas: [{ label: "Enroll Now", href: "{{enrollUrl}}" }],
  },
  {
    slug: "cobra_notice",
    componentName: "CobraNoticeEmail",
    category: "Benefits",
    subject: "COBRA continuation coverage notice",
    preheader: "Review continuation coverage rights and election deadlines.",
    title: "COBRA continuation coverage notice",
    requiredProps: ["employeeName", "planCosts", "electionDeadline", "qualifyingEventDate", "cobraUrl"],
    blocks: [
      { type: "legal", value: "This notice contains important information about your right to continue health care coverage under COBRA after your qualifying event on {{qualifyingEventDate}}. You generally have 60 days to elect continuation coverage." },
      { type: "table", rows: [{ label: "Qualified beneficiary", value: "{{employeeName}}" }, { label: "Plan costs", value: "{{planCosts}}" }, { label: "Election deadline", value: "{{electionDeadline}}" }] },
    ],
    ctas: [{ label: "View COBRA Notice", href: "{{cobraUrl}}" }],
  },
  {
    slug: "candidate_application_received",
    componentName: "CandidateApplicationReceivedEmail",
    category: "Hiring",
    subject: "We received your application for {{role}}",
    preheader: "{{companyName}} received your application.",
    title: "We received your application",
    requiredProps: ["candidateName", "companyName", "role", "careersUrl"],
    blocks: [
      { type: "text", value: "Hi {{candidateName}}, thanks for applying to {{role}} at {{companyName}}." },
      { type: "list", title: "What happens next", items: ["Our hiring team reviews your application", "We will contact you if there is a fit", "You can keep exploring open roles anytime"] },
    ],
    ctas: [{ label: "View Open Roles", href: "{{careersUrl}}" }],
  },
  {
    slug: "interview_scheduled",
    componentName: "InterviewScheduledEmail",
    category: "Hiring",
    subject: "Interview scheduled for {{interviewDate}}",
    preheader: "Your interview for {{role}} is scheduled.",
    title: "Interview scheduled",
    requiredProps: ["candidateName", "role", "interviewDate", "interviewTime", "locationOrVideoLink", "interviewers", "calendarUrl"],
    blocks: [{ type: "table", rows: [{ label: "Candidate", value: "{{candidateName}}" }, { label: "Role", value: "{{role}}" }, { label: "When", value: "{{interviewDate}} at {{interviewTime}}" }, { label: "Location", value: "{{locationOrVideoLink}}" }, { label: "Interviewers", value: "{{interviewers}}" }] }],
    ctas: [{ label: "Add to Calendar", href: "{{calendarUrl}}" }],
  },
  {
    slug: "offer_letter_sent",
    componentName: "OfferLetterSentEmail",
    category: "Hiring",
    subject: "Your offer from {{companyName}} is ready",
    preheader: "Review and sign your offer for {{role}}.",
    title: "Your offer from {{companyName}} is ready",
    tone: "success",
    requiredProps: ["candidateName", "companyName", "role", "reviewOfferUrl"],
    blocks: [{ type: "text", value: "Congratulations {{candidateName}}! Your offer for {{role}} at {{companyName}} is ready to review and sign." }],
    ctas: [{ label: "Review & Sign Offer", href: "{{reviewOfferUrl}}" }],
  },
  {
    slug: "offer_accepted_hr_notify",
    componentName: "OfferAcceptedHrNotifyEmail",
    category: "Hiring",
    subject: "{{candidateName}} accepted the offer!",
    preheader: "Start onboarding for {{candidateName}}.",
    title: "{{candidateName}} accepted the offer!",
    tone: "success",
    requiredProps: ["candidateName", "role", "startDate", "startOnboardingUrl"],
    blocks: [{ type: "table", rows: [{ label: "Candidate", value: "{{candidateName}}" }, { label: "Role", value: "{{role}}" }, { label: "Start date", value: "{{startDate}}" }] }],
    ctas: [{ label: "Start Onboarding", href: "{{startOnboardingUrl}}" }],
  },
  {
    slug: "offer_declined_hr_notify",
    componentName: "OfferDeclinedHrNotifyEmail",
    category: "Hiring",
    subject: "{{candidateName}} declined the offer",
    preheader: "Review the decline reason and candidate profile.",
    title: "{{candidateName}} declined the offer",
    requiredProps: ["candidateName", "role", "declineReason", "candidateProfileUrl"],
    blocks: [{ type: "table", rows: [{ label: "Candidate", value: "{{candidateName}}" }, { label: "Role", value: "{{role}}" }, { label: "Reason", value: "{{declineReason}}" }] }],
    ctas: [{ label: "Open Candidate", href: "{{candidateProfileUrl}}" }],
  },
  {
    slug: "candidate_rejected",
    componentName: "CandidateRejectedEmail",
    category: "Hiring",
    subject: "Update on your application to {{companyName}}",
    preheader: "Thank you for your interest in {{role}}.",
    title: "Update on your application",
    requiredProps: ["candidateName", "companyName", "role", "careersUrl"],
    blocks: [
      { type: "text", value: "Hi {{candidateName}}, thank you for your interest in {{role}} at {{companyName}}. We have decided to move forward with other candidates for this role." },
      { type: "text", value: "We appreciate the time you invested and encourage you to apply for future openings." },
    ],
    ctas: [{ label: "View Future Roles", href: "{{careersUrl}}" }],
  },
  {
    slug: "background_check_initiated",
    componentName: "BackgroundCheckInitiatedEmail",
    category: "Hiring",
    subject: "Background check initiated",
    preheader: "{{provider}} has started your background check.",
    title: "Background check initiated",
    requiredProps: ["candidateName", "provider", "estimatedTimeline", "statusUrl"],
    blocks: [{ type: "text", value: "Hi {{candidateName}}, {{provider}} has initiated your background check. Estimated timeline: {{estimatedTimeline}}." }],
    ctas: [{ label: "View Status", href: "{{statusUrl}}" }],
  },
  {
    slug: "compliance_alert_critical",
    componentName: "ComplianceAlertCriticalEmail",
    category: "Compliance & Billing",
    subject: "Action required - compliance issue",
    preheader: "{{severity}} compliance issue needs action by {{dueDate}}.",
    title: "Action required - compliance issue",
    tone: "danger",
    requiredProps: ["issueDescription", "severity", "dueDate", "resolveUrl"],
    blocks: [
      { type: "alert", value: "{{severity}}: {{issueDescription}}" },
      { type: "table", rows: [{ label: "Due", value: "{{dueDate}}" }, { label: "Severity", value: "{{severity}}" }] },
    ],
    ctas: [{ label: "Resolve Now", href: "{{resolveUrl}}", tone: "danger" }],
  },
  {
    slug: "i9_expiring_warning",
    componentName: "I9ExpiringWarningEmail",
    category: "Compliance & Billing",
    subject: "I-9 document expiring for {{employeeName}}",
    preheader: "{{documentName}} expires on {{expiryDate}}.",
    title: "I-9 document expiring for {{employeeName}}",
    tone: "danger",
    requiredProps: ["employeeName", "documentName", "expiryDate", "reverifyUrl"],
    blocks: [{ type: "table", rows: [{ label: "Employee", value: "{{employeeName}}" }, { label: "Document", value: "{{documentName}}" }, { label: "Expiry", value: "{{expiryDate}}" }] }],
    ctas: [{ label: "Re-verify", href: "{{reverifyUrl}}" }],
  },
  {
    slug: "filing_deadline_reminder",
    componentName: "FilingDeadlineReminderEmail",
    category: "Compliance & Billing",
    subject: "Tax filing due in {{daysUntilDue}} days",
    preheader: "{{formType}} is due {{dueDate}}.",
    title: "Tax filing due in {{daysUntilDue}} days",
    requiredProps: ["daysUntilDue", "formType", "dueDate", "jurisdiction", "filingUrl"],
    blocks: [{ type: "table", rows: [{ label: "Form", value: "{{formType}}" }, { label: "Due date", value: "{{dueDate}}" }, { label: "Jurisdiction", value: "{{jurisdiction}}" }] }],
    ctas: [{ label: "Prepare Filing", href: "{{filingUrl}}" }],
  },
  {
    slug: "invoice_created",
    componentName: "InvoiceCreatedEmail",
    category: "Compliance & Billing",
    subject: "Your CircleWorks invoice is ready",
    preheader: "{{amount}} for {{billingPeriod}} is due {{dueDate}}.",
    title: "Your CircleWorks invoice is ready",
    requiredProps: ["amount", "billingPeriod", "dueDate", "invoiceUrl"],
    blocks: [{ type: "table", rows: [{ label: "Amount", value: "{{amount}}" }, { label: "Period", value: "{{billingPeriod}}" }, { label: "Due date", value: "{{dueDate}}" }] }],
    ctas: [{ label: "View Invoice", href: "{{invoiceUrl}}" }],
  },
  {
    slug: "payment_failed",
    componentName: "PaymentFailedEmail",
    category: "Compliance & Billing",
    subject: "Payment failed - update billing info",
    preheader: "Payment of {{amount}} failed.",
    title: "Payment failed - update billing info",
    tone: "danger",
    requiredProps: ["amount", "failureReason", "updatePaymentUrl"],
    blocks: [{ type: "alert", value: "Payment of {{amount}} failed: {{failureReason}}" }],
    ctas: [{ label: "Update Payment Method", href: "{{updatePaymentUrl}}", tone: "danger" }],
  },
  {
    slug: "trial_expiring",
    componentName: "TrialExpiringEmail",
    category: "Compliance & Billing",
    subject: "Your free trial ends in 3 days",
    preheader: "Upgrade before {{trialEndDate}} to keep premium features.",
    title: "Your free trial ends in 3 days",
    requiredProps: ["trialEndDate", "featuresSummary", "upgradeUrl"],
    blocks: [
      { type: "text", value: "Your trial ends on {{trialEndDate}}." },
      { type: "list", title: "Keep access to", items: ["{{featuresSummary}}"] },
    ],
    ctas: [{ label: "Upgrade Now", href: "{{upgradeUrl}}" }],
  },
  {
    slug: "subscription_upgraded",
    componentName: "SubscriptionUpgradedEmail",
    category: "Compliance & Billing",
    subject: "Welcome to {{planName}}!",
    preheader: "Your upgraded CircleWorks plan is active.",
    title: "Welcome to {{planName}}!",
    tone: "success",
    requiredProps: ["planName", "featuresUnlocked", "exploreUrl"],
    blocks: [{ type: "list", title: "Features unlocked", items: ["{{featuresUnlocked}}"] }],
    ctas: [{ label: "Explore Features", href: "{{exploreUrl}}" }],
  },
  {
    slug: "subscription_cancelled",
    componentName: "SubscriptionCancelledEmail",
    category: "Compliance & Billing",
    subject: "Subscription cancelled - we're sad to see you go",
    preheader: "Your cancellation is effective {{effectiveDate}}.",
    title: "Subscription cancelled",
    requiredProps: ["effectiveDate", "dataExportUrl", "winBackOffer"],
    blocks: [
      { type: "text", value: "Your CircleWorks subscription will end on {{effectiveDate}}." },
      { type: "alert", value: "{{winBackOffer}}" },
    ],
    ctas: [{ label: "Export Data", href: "{{dataExportUrl}}" }],
  },
  {
    slug: "data_export_ready",
    componentName: "DataExportReadyEmail",
    category: "Compliance & Billing",
    subject: "Your data export is ready",
    preheader: "Download link expires in {{expiresAt}}.",
    title: "Your data export is ready",
    requiredProps: ["downloadUrl", "expiresAt"],
    blocks: [{ type: "alert", value: "This download link expires in {{expiresAt}}." }],
    ctas: [{ label: "Download Export", href: "{{downloadUrl}}" }],
  },
  {
    slug: "security_alert",
    componentName: "SecurityAlertEmail",
    category: "Compliance & Billing",
    subject: "New login from unfamiliar device",
    preheader: "{{device}} login detected from {{location}}.",
    title: "New login from unfamiliar device",
    tone: "danger",
    requiredProps: ["location", "device", "timestamp", "wasThisYouUrl", "secureAccountUrl"],
    blocks: [{ type: "table", rows: [{ label: "Location", value: "{{location}}" }, { label: "Device", value: "{{device}}" }, { label: "Time", value: "{{timestamp}}" }] }],
    ctas: [{ label: "Was this you?", href: "{{wasThisYouUrl}}" }, { label: "Secure Account", href: "{{secureAccountUrl}}", tone: "danger" }],
  },
] as const;

export const emailTemplateDefinitionBySlug = new Map<EmailTemplateSlug, EmailTemplateDefinition>(
  emailTemplateDefinitions.map((definition) => [definition.slug, definition]),
);

export function getEmailTemplateDefinition(slug: EmailTemplateSlug) {
  const definition = emailTemplateDefinitionBySlug.get(slug);
  if (!definition) {
    throw new Error(`Unknown CircleWorks email template: ${slug}`);
  }
  return definition;
}
