import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { PayrollRunReportData } from "./payroll-run-report-types";
import { currency } from "./build-payroll-run-report-data";

const navy = "#0c1e3c";
const muted = "#64748b";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 9, fontFamily: "Helvetica", color: "#0f172a" },
  headerBar: {
    backgroundColor: navy,
    margin: -40,
    marginBottom: 24,
    padding: 20,
    paddingLeft: 40,
    paddingRight: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brandRow: { flexDirection: "row", alignItems: "center" },
  logoMark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 9,
  },
  logoText: { color: navy, fontSize: 8, fontFamily: "Helvetica-Bold" },
  brand: { color: "#ffffff", fontSize: 18, fontFamily: "Helvetica-Bold" },
  brandSub: { color: "#94a3b8", fontSize: 9, marginTop: 4 },
  coverTitle: { fontSize: 22, fontFamily: "Helvetica-Bold", marginTop: 32, color: navy },
  coverMeta: { marginTop: 16, fontSize: 11, color: muted },
  coverBig: { marginTop: 28, fontSize: 28, fontFamily: "Helvetica-Bold", color: navy },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: navy,
    marginTop: 20,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingBottom: 4,
  },
  row: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: "#f1f5f9", paddingVertical: 5 },
  th: { flexDirection: "row", paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: "#cbd5e1" },
  thText: { fontFamily: "Helvetica-Bold", fontSize: 8, color: muted },
  cellName: { width: "32%" },
  cellNum: { width: "17%", textAlign: "right" },
  cellRight: { flex: 1, textAlign: "right", fontFamily: "Helvetica" },
  summaryBox: {
    marginTop: 12,
    padding: 12,
    backgroundColor: "#f8fafc",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  summaryRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  foot: {
    position: "absolute",
    bottom: 28,
    left: 40,
    right: 40,
    fontSize: 8,
    color: muted,
    textAlign: "center",
    borderTopWidth: 0.5,
    borderTopColor: "#e2e8f0",
    paddingTop: 8,
  },
});

function Header({ label }: { label: string }) {
  return (
    <View style={styles.headerBar}>
      <View style={styles.brandRow}>
        <View style={styles.logoMark}>
          <Text style={styles.logoText}>CW</Text>
        </View>
        <View>
          <Text style={styles.brand}>CircleWorks</Text>
          <Text style={styles.brandSub}>Payroll run report</Text>
        </View>
      </View>
      <Text style={{ color: "#e2e8f0", fontSize: 10 }}>{label}</Text>
    </View>
  );
}

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

export function PayrollRunReportPdf({ data }: { data: PayrollRunReportData }) {
  const empChunks = chunk(data.employees, 14);

  return (
    <Document title={`Payroll Report ${data.runIdLabel}`} author="CircleWorks">
      <Page size="LETTER" style={styles.page}>
        <Header label={data.runIdLabel} />
        <Text style={styles.coverTitle}>Payroll register</Text>
        <Text style={styles.coverMeta}>{data.companyName}</Text>
        <Text style={styles.coverMeta}>Pay period: {data.payPeriodLabel}</Text>
        <Text style={styles.coverMeta}>Run / check date: {data.runDateLabel}</Text>
        <Text style={styles.coverBig}>${currency(data.totalPayroll)}</Text>
        <Text style={{ ...styles.coverMeta, marginTop: 8 }}>Total payroll (gross + employer taxes & benefits)</Text>
        <Text style={styles.foot}>Generated by CircleWorks · Confidential</Text>
      </Page>

      <Page size="LETTER" style={styles.page}>
        <Header label="Summary" />
        <Text style={styles.sectionTitle}>Summary</Text>
        <View style={styles.summaryBox}>
          <View style={styles.summaryRow}>
            <Text>Total gross</Text>
            <Text>${currency(data.totalGross)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text>Total taxes (employee)</Text>
            <Text>${currency(data.totalTaxes)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text>Total deductions</Text>
            <Text>${currency(data.totalDeductions)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>Total net pay</Text>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>${currency(data.totalNet)}</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Employer costs</Text>
        <View style={styles.summaryBox}>
          <View style={styles.summaryRow}>
            <Text>FICA (employer match)</Text>
            <Text>${currency(data.employerFica)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text>FUTA</Text>
            <Text>${currency(data.employerFuta)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text>SUTA (est.)</Text>
            <Text>${currency(data.employerSuta)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text>Benefits contributions</Text>
            <Text>${currency(data.employerBenefits)}</Text>
          </View>
        </View>
        <Text style={styles.foot}>Generated by CircleWorks · {data.runIdLabel}</Text>
      </Page>

      {empChunks.map((rows, pageIdx) => (
        <Page key={pageIdx} size="LETTER" style={styles.page}>
          <Header label={`Employees (${pageIdx + 1}/${empChunks.length})`} />
          <Text style={styles.sectionTitle}>Employee detail</Text>
          <View style={styles.th}>
            <Text style={[styles.thText, styles.cellName]}>Employee</Text>
            <Text style={[styles.thText, styles.cellNum]}>Gross</Text>
            <Text style={[styles.thText, styles.cellNum]}>Taxes</Text>
            <Text style={[styles.thText, styles.cellNum]}>Deduct.</Text>
            <Text style={[styles.thText, styles.cellNum]}>Net</Text>
          </View>
          {rows.map((e, i) => (
            <View key={i} style={styles.row} wrap={false}>
              <Text style={styles.cellName}>{e.name}</Text>
              <Text style={styles.cellNum}>${currency(e.gross)}</Text>
              <Text style={styles.cellNum}>${currency(e.taxes)}</Text>
              <Text style={styles.cellNum}>${currency(e.deductions)}</Text>
              <Text style={styles.cellNum}>${currency(e.net)}</Text>
            </View>
          ))}
          <Text style={styles.foot}>Generated by CircleWorks · {data.runIdLabel}</Text>
        </Page>
      ))}

      {data.glMappingConfigured && data.journalLines.length > 0 ? (
        <Page size="LETTER" style={styles.page}>
          <Header label="GL" />
          <Text style={styles.sectionTitle}>Journal entry preview</Text>
          <Text style={{ fontSize: 8, color: muted, marginBottom: 10 }}>
            Based on configured payroll → GL mapping. Final entry may vary by cash posting date.
          </Text>
          <View style={styles.th}>
            <Text style={[styles.thText, { width: "14%" }]}>Account</Text>
            <Text style={[styles.thText, { width: "40%" }]}>Description</Text>
            <Text style={[styles.thText, styles.cellRight]}>Debit</Text>
            <Text style={[styles.thText, styles.cellRight]}>Credit</Text>
          </View>
          {data.journalLines.map((line, i) => (
            <View key={i} style={styles.row} wrap={false}>
              <Text style={{ width: "14%" }}>{line.account}</Text>
              <Text style={{ width: "40%" }}>{line.description}</Text>
              <Text style={styles.cellRight}>{line.debit ? `$${currency(line.debit)}` : "—"}</Text>
              <Text style={styles.cellRight}>{line.credit ? `$${currency(line.credit)}` : "—"}</Text>
            </View>
          ))}
          <Text style={styles.foot}>Generated by CircleWorks · {data.runIdLabel}</Text>
        </Page>
      ) : (
        <Page size="LETTER" style={styles.page}>
          <Header label="GL" />
          <Text style={styles.sectionTitle}>Journal entry preview</Text>
          <Text style={{ fontSize: 10, color: muted, marginTop: 12 }}>
            GL mapping is not configured for this company. Map accounts under Payroll → GL Mapping to include a journal
            preview on this report.
          </Text>
          <Text style={styles.foot}>Generated by CircleWorks · {data.runIdLabel}</Text>
        </Page>
      )}
    </Document>
  );
}
