export const SETTINGS_NAV_ITEMS = [
  { label: "Company", href: "/settings/company" },
  { label: "Profile", href: "/settings/profile" },
  { label: "Users", href: "/settings/users" },
  { label: "Roles", href: "/settings/roles" },
  { label: "Departments", href: "/settings/departments" },
  { label: "Locations", href: "/settings/locations" },
  { label: "Billing", href: "/settings/billing" },
  { label: "Bank", href: "/settings/bank" },
  { label: "Pay Schedules", href: "/settings/pay-schedules" },
  { label: "Payroll Unions", href: "/settings/payroll/unions" },
  { label: "Time Settings", href: "/settings/time" },
  { label: "Notifications", href: "/settings/notifications" },
  { label: "Integrations", href: "/settings/integrations" },
  { label: "API", href: "/settings/api" },
  { label: "SSO", href: "/settings/sso" },
  { label: "Security Devices", href: "/settings/security/devices" },
  { label: "Assets", href: "/settings/assets" },
  { label: "Import", href: "/settings/import" },
  { label: "Custom Fields", href: "/settings/custom-fields" },
  { label: "Workflows", href: "/settings/workflows" },
  { label: "Announcements", href: "/settings/announcements" },
  { label: "Audit Log", href: "/settings/audit-log" },
  { label: "Agency Clients", href: "/settings/agency/clients" },
];
