import { NextResponse } from "next/server";

export async function GET() {
  const summary = {
    totalClients: 8,
    activePayrollsThisWeek: 5,
    pendingApprovals: 4,
    taxDeadlines: 3,
    totalEmployees: 293,
    totalContractors: 90,
    totalPayrollVolumeThisMonth: 2511000,
    clientsByStatus: {
      on_time: 5,
      action_required: 2,
      issue: 1,
    },
    upcomingDeadlines: [
      {
        id: "dl_001",
        date: "2026-04-16",
        type: "payroll",
        title: "Payroll Run — Pinnacle Tech Solutions",
        client: "Pinnacle Tech Solutions",
        clientSlug: "pinnacle-tech",
        severity: "critical",
        description: "Bi-weekly payroll for 62 employees. Bank debit required by 4pm ET.",
      },
      {
        id: "dl_002",
        date: "2026-04-17",
        type: "payroll",
        title: "Payroll Run — Vertex Media Group",
        client: "Vertex Media Group",
        clientSlug: "vertex-media",
        severity: "normal",
        description: "Semi-monthly payroll for 47 employees.",
      },
      {
        id: "dl_003",
        date: "2026-04-18",
        type: "payroll",
        title: "Payroll Run — Nova Studios Inc.",
        client: "Nova Studios Inc.",
        clientSlug: "nova-studios",
        severity: "warning",
        description: "Bi-weekly payroll. 2 pending items need review.",
      },
      {
        id: "dl_004",
        date: "2026-04-19",
        type: "payroll",
        title: "Payroll Run — BrightPath Education",
        client: "BrightPath Education",
        clientSlug: "brightpath-edu",
        severity: "warning",
        description: "Semi-monthly payroll. New hire onboarding pending.",
      },
      {
        id: "dl_005",
        date: "2026-04-20",
        type: "payroll",
        title: "Payroll Run — Coastal Eats Co.",
        client: "Coastal Eats Co.",
        clientSlug: "coastal-eats",
        severity: "normal",
        description: "Bi-weekly payroll for 34 employees.",
      },
      {
        id: "dl_006",
        date: "2026-04-21",
        type: "payroll",
        title: "Payroll Run — Ironclad Construction",
        client: "Ironclad Construction",
        clientSlug: "ironclad-construction",
        severity: "normal",
        description: "Weekly payroll for 89 employees + 34 contractors.",
      },
      {
        id: "dl_007",
        date: "2026-04-25",
        type: "tax",
        title: "CA State Tax Deposit — Vertex Media",
        client: "Vertex Media Group",
        clientSlug: "vertex-media",
        severity: "normal",
        description: "California employer payroll tax deposit due.",
      },
      {
        id: "dl_008",
        date: "2026-04-27",
        type: "tax",
        title: "NY Quarterly Filing — Nova Studios",
        client: "Nova Studios Inc.",
        clientSlug: "nova-studios",
        severity: "warning",
        description: "NYS-45 Quarterly Combined Withholding & Wage Reporting.",
      },
      {
        id: "dl_009",
        date: "2026-04-30",
        type: "compliance",
        title: "Q1 941 Filing Deadline — All Clients",
        client: "All Clients",
        clientSlug: "",
        severity: "critical",
        description: "Federal Form 941 quarterly filing for all clients. Ensure all payrolls reconciled.",
      },
      {
        id: "dl_010",
        date: "2026-05-01",
        type: "tax",
        title: "FL Reemployment Tax — Coastal Eats",
        client: "Coastal Eats Co.",
        clientSlug: "coastal-eats",
        severity: "normal",
        description: "Florida reemployment tax quarterly filing.",
      },
      {
        id: "dl_011",
        date: "2026-05-05",
        type: "compliance",
        title: "W-2 Corrections Deadline — BrightPath",
        client: "BrightPath Education",
        clientSlug: "brightpath-edu",
        severity: "warning",
        description: "Deadline to file corrected W-2c forms for 2025.",
      },
      {
        id: "dl_012",
        date: "2026-05-10",
        type: "benefits",
        title: "Benefits Renewal Review — Pinnacle Tech",
        client: "Pinnacle Tech Solutions",
        clientSlug: "pinnacle-tech",
        severity: "normal",
        description: "Annual benefits renewal package review and employee communication.",
      },
    ],
    pendingPayrollRuns: [
      {
        id: "pr_001",
        clientId: "cl_002",
        client: "Nova Studios Inc.",
        clientSlug: "nova-studios",
        payPeriod: "Apr 1 – Apr 15, 2026",
        employeeCount: 23,
        grossAmount: 94200,
        netAmount: 67410,
        taxes: 18840,
        deductions: 7950,
        status: "awaiting_approval",
        submittedAt: "2026-04-14T09:30:00Z",
        submittedBy: "Sarah Chen",
        flags: ["New hire added", "OT detected for 2 employees"],
      },
      {
        id: "pr_002",
        clientId: "cl_002",
        client: "Nova Studios Inc.",
        clientSlug: "nova-studios",
        payPeriod: "Apr 1 – Apr 15, 2026 (Contractors)",
        employeeCount: 8,
        grossAmount: 28400,
        netAmount: 28400,
        taxes: 0,
        deductions: 0,
        status: "awaiting_approval",
        submittedAt: "2026-04-14T09:45:00Z",
        submittedBy: "Sarah Chen",
        flags: ["1 new contractor onboarded"],
      },
      {
        id: "pr_003",
        clientId: "cl_004",
        client: "Pinnacle Tech Solutions",
        clientSlug: "pinnacle-tech",
        payPeriod: "Apr 1 – Apr 15, 2026",
        employeeCount: 62,
        grossAmount: 312000,
        netAmount: 224640,
        taxes: 62400,
        deductions: 24960,
        status: "awaiting_approval",
        submittedAt: "2026-04-14T10:15:00Z",
        submittedBy: "Mike Davis",
        flags: ["Tax jurisdiction change for 1 employee"],
      },
      {
        id: "pr_004",
        clientId: "cl_006",
        client: "BrightPath Education",
        clientSlug: "brightpath-edu",
        payPeriod: "Apr 1 – Apr 15, 2026",
        employeeCount: 19,
        grossAmount: 67800,
        netAmount: 48816,
        taxes: 13560,
        deductions: 5424,
        status: "awaiting_approval",
        submittedAt: "2026-04-14T11:00:00Z",
        submittedBy: "Lisa Park",
        flags: [],
      },
    ],
  };

  return NextResponse.json(summary);
}
