import { NextResponse } from "next/server";

const MOCK_CLIENTS = [
  {
    id: "cl_001",
    slug: "vertex-media",
    name: "Vertex Media Group",
    logoUrl: "https://api.dicebear.com/7.x/identicon/svg?seed=vertex&backgroundColor=1e293b",
    industry: "Digital Media",
    plan: "Premium",
    employeeCount: 47,
    contractorCount: 12,
    status: "on_time" as const,
    statusLabel: "Payroll On Time",
    nextPayrollDate: "2026-04-17",
    nextPayrollAmount: 187500,
    lastPayrollDate: "2026-04-03",
    state: "CA",
    ein: "82-*****41",
    monthlyPayrollVolume: 375000,
    pendingApprovals: 0,
    setupComplete: true,
  },
  {
    id: "cl_002",
    slug: "nova-studios",
    name: "Nova Studios Inc.",
    logoUrl: "https://api.dicebear.com/7.x/identicon/svg?seed=nova&backgroundColor=1e293b",
    industry: "Creative Agency",
    plan: "Growth",
    employeeCount: 23,
    contractorCount: 8,
    status: "action_required" as const,
    statusLabel: "Action Required",
    nextPayrollDate: "2026-04-18",
    nextPayrollAmount: 94200,
    lastPayrollDate: "2026-04-04",
    state: "NY",
    ein: "45-*****18",
    monthlyPayrollVolume: 188400,
    pendingApprovals: 2,
    setupComplete: true,
  },
  {
    id: "cl_003",
    slug: "ember-collective",
    name: "Ember Collective LLC",
    logoUrl: "https://api.dicebear.com/7.x/identicon/svg?seed=ember&backgroundColor=1e293b",
    industry: "Marketing",
    plan: "Starter",
    employeeCount: 8,
    contractorCount: 3,
    status: "on_time" as const,
    statusLabel: "Payroll On Time",
    nextPayrollDate: "2026-04-22",
    nextPayrollAmount: 32000,
    lastPayrollDate: "2026-04-08",
    state: "TX",
    ein: "71-*****93",
    monthlyPayrollVolume: 64000,
    pendingApprovals: 0,
    setupComplete: true,
  },
  {
    id: "cl_004",
    slug: "pinnacle-tech",
    name: "Pinnacle Tech Solutions",
    logoUrl: "https://api.dicebear.com/7.x/identicon/svg?seed=pinnacle&backgroundColor=1e293b",
    industry: "SaaS",
    plan: "Premium",
    employeeCount: 62,
    contractorCount: 19,
    status: "issue" as const,
    statusLabel: "Issue",
    nextPayrollDate: "2026-04-16",
    nextPayrollAmount: 312000,
    lastPayrollDate: "2026-04-02",
    state: "WA",
    ein: "91-*****55",
    monthlyPayrollVolume: 624000,
    pendingApprovals: 1,
    setupComplete: true,
  },
  {
    id: "cl_005",
    slug: "coastal-eats",
    name: "Coastal Eats Co.",
    logoUrl: "https://api.dicebear.com/7.x/identicon/svg?seed=coastal&backgroundColor=1e293b",
    industry: "Restaurant Group",
    plan: "Growth",
    employeeCount: 34,
    contractorCount: 5,
    status: "on_time" as const,
    statusLabel: "Payroll On Time",
    nextPayrollDate: "2026-04-20",
    nextPayrollAmount: 78500,
    lastPayrollDate: "2026-04-06",
    state: "FL",
    ein: "65-*****27",
    monthlyPayrollVolume: 157000,
    pendingApprovals: 0,
    setupComplete: true,
  },
  {
    id: "cl_006",
    slug: "brightpath-edu",
    name: "BrightPath Education",
    logoUrl: "https://api.dicebear.com/7.x/identicon/svg?seed=brightpath&backgroundColor=1e293b",
    industry: "EdTech",
    plan: "Growth",
    employeeCount: 19,
    contractorCount: 7,
    status: "action_required" as const,
    statusLabel: "Action Required",
    nextPayrollDate: "2026-04-19",
    nextPayrollAmount: 67800,
    lastPayrollDate: "2026-04-05",
    state: "CO",
    ein: "84-*****62",
    monthlyPayrollVolume: 135600,
    pendingApprovals: 1,
    setupComplete: true,
  },
  {
    id: "cl_007",
    slug: "ironclad-construction",
    name: "Ironclad Construction",
    logoUrl: "https://api.dicebear.com/7.x/identicon/svg?seed=ironclad&backgroundColor=1e293b",
    industry: "Construction",
    plan: "Premium",
    employeeCount: 89,
    contractorCount: 34,
    status: "on_time" as const,
    statusLabel: "Payroll On Time",
    nextPayrollDate: "2026-04-21",
    nextPayrollAmount: 445000,
    lastPayrollDate: "2026-04-07",
    state: "IL",
    ein: "36-*****88",
    monthlyPayrollVolume: 890000,
    pendingApprovals: 0,
    setupComplete: true,
  },
  {
    id: "cl_008",
    slug: "sapphire-wellness",
    name: "Sapphire Wellness Spa",
    logoUrl: "https://api.dicebear.com/7.x/identicon/svg?seed=sapphire&backgroundColor=1e293b",
    industry: "Health & Wellness",
    plan: "Starter",
    employeeCount: 11,
    contractorCount: 2,
    status: "on_time" as const,
    statusLabel: "Payroll On Time",
    nextPayrollDate: "2026-04-23",
    nextPayrollAmount: 38500,
    lastPayrollDate: "2026-04-09",
    state: "AZ",
    ein: "86-*****14",
    monthlyPayrollVolume: 77000,
    pendingApprovals: 0,
    setupComplete: true,
  },
];

export async function GET() {
  return NextResponse.json({ clients: MOCK_CLIENTS });
}
